"""
Lumina AI — FastAPI Backend (v9 — Lightricks LTX-2 Native API)
===============================================================

VIDEO GENERATION
  Endpoint : POST https://api.ltx.video/v1/text-to-video
  Auth     : Authorization: Bearer <LTX_API_KEY>
  Response : raw MP4 bytes (synchronous — no polling needed)
  Models   : ltx-2-fast  (up to 20s, cheaper)
             ltx-2-pro   (up to 10s, higher quality)

IMAGE GENERATION
  Since LTX-2 is video-only, images are generated by extracting the
  first frame of a short (6s) video using ffmpeg.

PROMPT ENHANCEMENT
  Uses Groq free tier (Llama 3 70B) if GROQ_API_KEY is set.
  Falls back to keyword extraction otherwise.
  Get a free Groq key at: https://console.groq.com/keys

SETUP
  1. Add LTX_API_KEY=ltx_... to your .env
  2. pip install -r requirements.txt
  3. uvicorn main:app --host 0.0.0.0 --port 8000
"""

import asyncio
import os
import re
import uuid
import logging
import time
import subprocess
from pathlib import Path
from typing import Dict
from contextlib import asynccontextmanager

import httpx
from dotenv import load_dotenv
from fastapi import BackgroundTasks, FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

load_dotenv()

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Directories
# ---------------------------------------------------------------------------
BASE_DIR      = Path(__file__).resolve().parent
GENERATED_DIR = BASE_DIR / "generated"
IMAGES_DIR    = GENERATED_DIR / "images"
VIDEOS_DIR    = GENERATED_DIR / "videos"
TEMP_DIR      = GENERATED_DIR / "temp"
STATIC_DIR    = BASE_DIR / "static"

for _d in [IMAGES_DIR, VIDEOS_DIR, TEMP_DIR, STATIC_DIR]:
    _d.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Config from .env
# ---------------------------------------------------------------------------
LTX_API_KEY      = os.getenv("LTX_API_KEY", "")
GROQ_API_KEY     = os.getenv("GROQ_API_KEY", "")    # free at console.groq.com/keys

LTX_API_BASE     = "https://api.ltx.video/v1"

VIDEO_MODEL      = os.getenv("VIDEO_MODEL",      "ltx-2-fast")
VIDEO_RESOLUTION = os.getenv("VIDEO_RESOLUTION", "1920x1080")
VIDEO_DURATION   = int(os.getenv("VIDEO_DURATION", "8"))
VIDEO_FPS        = int(os.getenv("VIDEO_FPS",       "25"))

IMAGE_MODEL      = os.getenv("IMAGE_MODEL",      "ltx-2-fast")
IMAGE_RESOLUTION = os.getenv("IMAGE_RESOLUTION", "1920x1080")
IMAGE_DURATION   = 6  # minimum — we only keep the first frame

HTTP_TIMEOUT = httpx.Timeout(connect=30.0, read=600.0, write=30.0, pool=5.0)

# ---------------------------------------------------------------------------
# Task store
# ---------------------------------------------------------------------------
tasks: Dict[str, dict] = {}

# ---------------------------------------------------------------------------
# Pydantic models
# ---------------------------------------------------------------------------
class GenerateRequest(BaseModel):
    text: str = Field(..., min_length=10, max_length=4000)
    type: str = Field(..., pattern="^(image|video)$")

class CancelResponse(BaseModel):
    task_id: str
    message: str

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------
def task_update(task_id: str, **kw) -> None:
    if task_id not in tasks:
        return
    tasks[task_id].update(kw)
    log.info("Task %s  status=%-12s  progress=%3d%%  msg=%s",
             task_id[:8], tasks[task_id].get("status", ""),
             tasks[task_id].get("progress", 0), kw.get("message", ""))

def is_cancelled(tid: str) -> bool:
    return tasks.get(tid, {}).get("cancelled", False)

def _ltx_headers() -> dict:
    if not LTX_API_KEY:
        raise RuntimeError("LTX_API_KEY not set in .env — get your key at https://console.ltx.video/")
    return {"Authorization": f"Bearer {LTX_API_KEY}", "Content-Type": "application/json"}

def _ffmpeg_available() -> bool:
    try:
        subprocess.run(["ffmpeg", "-version"], capture_output=True, check=True, timeout=5)
        return True
    except Exception:
        return False

# ---------------------------------------------------------------------------
# Prompt enhancement
# ---------------------------------------------------------------------------
async def enhance_prompt(text: str, mode: str) -> str:
    if GROQ_API_KEY:
        return await _enhance_with_groq(text, mode)
    return _keyword_prompt(text, mode)

async def _enhance_with_groq(text: str, mode: str) -> str:
    """
    Uses Groq's free tier API (Llama 3.3 70B) to generate a high-quality
    visual prompt from the selected article text.
    Free tier: ~14,400 requests/day. No credit card needed.
    Docs: https://console.groq.com/docs/openai
    """
    instruction = (
        "Write ONE concise video generation prompt (max 150 words) describing MOTION and CAMERA "
        "MOVEMENT for a video representing this scientific text. Describe what moves, how it moves, "
        "and camera behavior (e.g. 'slow push-in', 'pan across'). "
        "Style: cinematic, 4K, dramatic lighting, photorealistic. "
        "Output ONLY the prompt — no preamble, no markdown, no quotes."
        if mode == "video" else
        "Write ONE concise image generation prompt (max 150 words) that visually represents "
        "this scientific text. Include subject, lighting, style, and composition. "
        "Style: scientific illustration, photorealistic, bright white background, sharp focus, 4K. "
        "Output ONLY the prompt — no preamble, no markdown, no quotes."
    )
    payload = {
        "model": "llama-3.3-70b-versatile",   # free on Groq
        "max_tokens": 250,
        "temperature": 0.4,
        "messages": [
            {"role": "system", "content": "You are an expert visual prompt engineer for AI video and image generation."},
            {"role": "user",   "content": f"{instruction}\n\nScientific text:\n{text[:1500]}"},
        ],
    }
    for attempt in range(1, 4):
        try:
            async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as hc:
                resp = await hc.post(
                    "https://api.groq.com/openai/v1/chat/completions",
                    json=payload,
                    headers={"Authorization": f"Bearer {GROQ_API_KEY}",
                             "Content-Type": "application/json"},
                )
                resp.raise_for_status()
                content = resp.json()["choices"][0]["message"]["content"].strip()
                content = re.sub(r"^```[^\n]*\n?", "", content)
                content = re.sub(r"\n?```$", "", content).strip()
                content = content.strip('"\'')
                log.info("Groq prompt (attempt %d): %s...", attempt, content[:80])
                return content
        except Exception as exc:
            log.warning("Groq attempt %d/3: %s", attempt, exc)
            if attempt < 3:
                await asyncio.sleep(3 * attempt)
    return _keyword_prompt(text, mode)

def _keyword_prompt(text: str, mode: str) -> str:
    stop = {"the","a","an","and","or","but","in","on","at","to","for","of","with","by","from",
            "is","are","was","were","be","been","have","has","had","do","does","did","will",
            "would","could","should","may","might","this","that","these","those","it","its",
            "they","we","our","which","who","what","when","where","how","all","each","every",
            "both","few","more","most","other","some","such","no","not","only","same","so",
            "than","too","very","just","also","about","into","through","using"}
    words = re.findall(r"\b[A-Za-z][A-Za-z\-]{3,}\b", text)
    kw, seen = [], set()
    for w in words:
        lw = w.lower()
        if lw not in stop and lw not in seen:
            seen.add(lw); kw.append(w)
        if len(kw) >= 10: break
    core = ", ".join(kw[:8]) if kw else text[:120]
    if mode == "video":
        return (f"Scientific visualization of {core}. Camera slowly pushes in, "
                "particles and structures animate fluidly, cinematic lighting, vibrant colors, 4K. "
                "Synchronized ambient audio and subtle sound effects.")
    return (f"Detailed scientific illustration of {core}. "
            "Bright background, sharp focus, vibrant colors, photorealistic, 4K.")

# ---------------------------------------------------------------------------
# LTX-2 API call — synchronous, returns raw MP4 bytes
# ---------------------------------------------------------------------------
async def call_ltx_video(prompt: str, model: str, resolution: str, duration: int,
                          fps: int, task_id: str, progress_start: int, progress_end: int) -> bytes:
    """
    POST to https://api.ltx.video/v1/text-to-video
    The LTX-2 API is synchronous — the HTTP response body IS the video file (MP4).
    No polling or webhooks needed.
    """
    payload = {
        "prompt":         prompt,
        "model":          model,
        "duration":       duration,
        "resolution":     resolution,
        "fps":            fps,
        "generate_audio": True,
    }
    log.info("LTX-2 request: model=%s  res=%s  dur=%ds  fps=%d", model, resolution, duration, fps)

    # Animate progress bar while the synchronous request is in flight
    async def _progress_ticker():
        value = progress_start
        while value < progress_end - 5:
            await asyncio.sleep(5)
            value = min(value + 2, progress_end - 5)
            if task_id in tasks and not is_cancelled(task_id):
                tasks[task_id]["progress"] = value

    ticker = asyncio.create_task(_progress_ticker())
    try:
        async with httpx.AsyncClient(timeout=HTTP_TIMEOUT) as hc:
            resp = await hc.post(f"{LTX_API_BASE}/text-to-video", json=payload, headers=_ltx_headers())

        # Friendly error messages
        if resp.status_code == 401:
            raise RuntimeError("Invalid LTX API key — check LTX_API_KEY in .env")
        if resp.status_code == 402:
            raise RuntimeError("Insufficient LTX credits — top up at console.ltx.video")
        if resp.status_code == 422:
            raise RuntimeError("Content filtered by LTX safety system — try a different prompt")
        if resp.status_code == 429:
            raise RuntimeError("LTX rate limit reached — wait a moment and retry")
        if resp.status_code >= 400:
            try:
                err = resp.json().get("error", {}).get("message", resp.text[:200])
            except Exception:
                err = resp.text[:200]
            raise RuntimeError(f"LTX API error {resp.status_code}: {err}")

        data = resp.content
        if len(data) < 10_000:
            try:
                body = resp.json()
                raise RuntimeError(f"LTX returned unexpected response: {body}")
            except Exception:
                raise RuntimeError(
                    f"LTX returned only {len(data)} bytes — expected MP4. "
                    "Verify your API key and model/resolution/duration combination."
                )

        log.info("LTX-2 response: %d bytes", len(data))
        return data
    finally:
        ticker.cancel()
        try: await ticker
        except asyncio.CancelledError: pass

# ---------------------------------------------------------------------------
# Extract first frame as JPEG using ffmpeg
# ---------------------------------------------------------------------------
def extract_first_frame(mp4_path: str, out_path: str) -> None:
    cmd = ["ffmpeg", "-y", "-i", mp4_path, "-vframes", "1", "-q:v", "2", out_path]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    if r.returncode != 0:
        raise RuntimeError(f"ffmpeg frame extraction failed:\n{r.stderr[-400:]}")
    log.info("Frame extracted: %s", out_path)

# ---------------------------------------------------------------------------
# Burn text overlay onto video using ffmpeg drawtext filter
# ---------------------------------------------------------------------------
def burn_text_overlay(in_path: str, out_path: str, text: str) -> None:
    """
    Renders a clean caption bar at the bottom of the video.
    - White text, semi-transparent dark bar background
    - Auto word-wraps at ~60 chars per line
    - Uses the built-in ffmpeg monospace font (no external font file needed)
    """
    # Trim to max ~200 chars so it fits without overflow
    caption = text.strip()[:200].replace("'", "\\'").replace(":", "\\:").replace("\\", "\\\\")

    # drawtext filter: dark translucent box + white text, bottom-centred
    drawtext = (
        "drawtext="
        "text='{caption}':"
        "x=(w-text_w)/2:"
        "y=h-th-24:"
        "fontsize=28:"
        "fontcolor=white:"
        "box=1:"
        "boxcolor=black@0.55:"
        "boxborderw=10:"
        "line_spacing=6:"
        "fix_bounds=1"
    ).format(caption=caption)

    cmd = [
        "ffmpeg", "-y",
        "-i", in_path,
        "-vf", drawtext,
        "-c:v", "libx264", "-preset", "fast", "-crf", "20",
        "-c:a", "copy",
        "-movflags", "+faststart",
        out_path,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    if r.returncode != 0:
        raise RuntimeError(f"ffmpeg text overlay failed:\n{r.stderr[-600:]}")
    log.info("Text overlay burned: %s", out_path)

# ---------------------------------------------------------------------------
# Background task: IMAGE
# ---------------------------------------------------------------------------
async def _task_image(task_id: str, text: str) -> None:
    tmp_video = TEMP_DIR / f"{task_id}_tmp.mp4"
    try:
        task_update(task_id, status="running", progress=8, message="Crafting visual prompt...")
        prompt = await enhance_prompt(text, "image")
        if is_cancelled(task_id):
            task_update(task_id, status="cancelled", progress=0, message="Cancelled."); return

        task_update(task_id, progress=18, message=f"Generating image via LTX-2 ({IMAGE_MODEL})...")
        video_bytes = await call_ltx_video(
            prompt=prompt, model=IMAGE_MODEL, resolution=IMAGE_RESOLUTION,
            duration=IMAGE_DURATION, fps=25, task_id=task_id,
            progress_start=18, progress_end=85,
        )
        if is_cancelled(task_id):
            task_update(task_id, status="cancelled", progress=0, message="Cancelled."); return

        task_update(task_id, progress=86, message="Extracting image frame...")
        tmp_video.write_bytes(video_bytes)

        if _ffmpeg_available():
            fname    = f"{task_id}.jpg"
            out_path = IMAGES_DIR / fname
            extract_first_frame(str(tmp_video), str(out_path))
        else:
            # No ffmpeg — save first frame via Python (basic, lower quality)
            log.warning("ffmpeg not found — saving raw video bytes as fallback")
            fname    = f"{task_id}.mp4"
            out_path = IMAGES_DIR / fname
            out_path.write_bytes(video_bytes)

        task_update(task_id, status="completed", progress=100, message="Image generated!",
                    result={"type": "image", "url": f"/generated/images/{fname}",
                            "filename": fname, "revised_prompt": prompt, "model": IMAGE_MODEL})
    except asyncio.CancelledError:
        task_update(task_id, status="cancelled", progress=0, message="Cancelled.")
    except Exception as exc:
        log.exception("Image task %s failed", task_id)
        task_update(task_id, status="error", progress=0, message=str(exc), error=str(exc))
    finally:
        tmp_video.unlink(missing_ok=True)

# ---------------------------------------------------------------------------
# Background task: VIDEO
# ---------------------------------------------------------------------------
async def _task_video(task_id: str, text: str) -> None:
    tmp_raw = TEMP_DIR / f"{task_id}_raw.mp4"
    try:
        task_update(task_id, status="running", progress=5, message="Crafting cinematic prompt...")
        prompt = await enhance_prompt(text, "video")
        if is_cancelled(task_id):
            task_update(task_id, status="cancelled", progress=0, message="Cancelled."); return

        task_update(task_id, progress=15,
                    message=f"Generating {VIDEO_DURATION}s video with {VIDEO_MODEL}...")
        video_bytes = await call_ltx_video(
            prompt=prompt, model=VIDEO_MODEL, resolution=VIDEO_RESOLUTION,
            duration=VIDEO_DURATION, fps=VIDEO_FPS, task_id=task_id,
            progress_start=15, progress_end=88,
        )
        if is_cancelled(task_id):
            task_update(task_id, status="cancelled", progress=0, message="Cancelled."); return

        fname    = f"{task_id}.mp4"
        out_path = VIDEOS_DIR / fname

        if _ffmpeg_available():
            # Burn the selected article text as a caption overlay
            task_update(task_id, progress=90, message="Burning text overlay...")
            tmp_raw.write_bytes(video_bytes)
            loop = asyncio.get_event_loop()
            await loop.run_in_executor(
                None, burn_text_overlay,
                str(tmp_raw), str(out_path),
                # Use first 180 chars of the original selected text as caption
                text[:180].strip()
            )
            log.info("Video with overlay saved: %s", fname)
        else:
            # No ffmpeg — save raw video without overlay
            log.warning("ffmpeg not found — saving video without text overlay")
            out_path.write_bytes(video_bytes)

        log.info("Video saved: %s  %d bytes", fname, out_path.stat().st_size)

        task_update(task_id, status="completed", progress=100, message="Video generated!",
                    result={"type": "video", "url": f"/generated/videos/{fname}",
                            "filename": fname, "revised_prompt": prompt, "model": VIDEO_MODEL,
                            "duration": VIDEO_DURATION, "resolution": VIDEO_RESOLUTION})
    except asyncio.CancelledError:
        task_update(task_id, status="cancelled", progress=0, message="Cancelled.")
    except Exception as exc:
        log.exception("Video task %s failed", task_id)
        task_update(task_id, status="error", progress=0, message=str(exc), error=str(exc))
    finally:
        tmp_raw.unlink(missing_ok=True)

# ---------------------------------------------------------------------------
# App lifecycle
# ---------------------------------------------------------------------------
@asynccontextmanager
async def lifespan(app: FastAPI):
    idx = STATIC_DIR / "index.html"
    log.info("\n"
        "╔══════════════════════════════════════════════════════╗\n"
        "║       Lumina AI v9  (Lightricks LTX-2 Native)        ║\n"
        "╠══════════════════════════════════════════════════════╣\n"
        "║  LTX_API_KEY    : %-34s║\n"
        "║  Video model    : %-34s║\n"
        "║  Video settings : %ds  %s  %dfps%s║\n"
        "║  Prompt engine  : %-34s║\n"
        "║  ffmpeg         : %-34s║\n"
        "║  index.html     : %-34s║\n"
        "╚══════════════════════════════════════════════════════╝",
        "SET ✓" if LTX_API_KEY else "MISSING ✗ — add LTX_API_KEY to .env",
        VIDEO_MODEL,
        VIDEO_DURATION, VIDEO_RESOLUTION, VIDEO_FPS, " " * (14 - len(VIDEO_RESOLUTION)),
        "Groq Llama-3.3-70b ✓" if GROQ_API_KEY else "keyword fallback (set GROQ_API_KEY for better prompts)",
        "OK ✓" if _ffmpeg_available() else "MISSING ✗ (needed for image frame extraction)",
        "FOUND ✓" if idx.exists() else "MISSING — copy index.html to static/",
    )
    if not LTX_API_KEY:
        log.warning("⚠️  LTX_API_KEY not set! Get your key at https://console.ltx.video/")
    yield

# ---------------------------------------------------------------------------
# FastAPI app
# ---------------------------------------------------------------------------
app = FastAPI(title="Lumina AI", version="9.0.0", lifespan=lifespan)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

@app.post("/api/generate")
async def generate(req: GenerateRequest, bg: BackgroundTasks):
    if not LTX_API_KEY:
        raise HTTPException(503, detail="LTX_API_KEY not configured. Add it to your .env file.")
    task_id = str(uuid.uuid4())
    tasks[task_id] = {"task_id": task_id, "type": req.type,
                       "text": req.text[:200] + ("..." if len(req.text) > 200 else ""),
                       "status": "pending", "progress": 0, "message": "Queued...",
                       "result": None, "error": None, "cancelled": False,
                       "created_at": time.time()}
    if req.type == "image":
        bg.add_task(_task_image, task_id, req.text)
    else:
        bg.add_task(_task_video, task_id, req.text)
    return {"task_id": task_id, "type": req.type}

@app.get("/api/status/{task_id}")
async def get_status(task_id: str):
    if task_id not in tasks:
        raise HTTPException(404, "Task not found.")
    return tasks[task_id]

@app.post("/api/cancel/{task_id}", response_model=CancelResponse)
async def cancel_task(task_id: str):
    """
    Sets the cancelled flag. Because LTX-2 is synchronous, the in-flight HTTP
    request can't be stopped mid-flight, but the task will not save its result.
    """
    if task_id not in tasks:
        raise HTTPException(404, "Task not found.")
    t = tasks[task_id]
    if t["status"] in ("completed", "cancelled", "error"):
        return CancelResponse(task_id=task_id, message=f"Already finished: {t['status']}")
    tasks[task_id]["cancelled"] = True
    return CancelResponse(task_id=task_id, message="Cancel signal sent.")

@app.get("/api/tasks")
async def list_tasks():
    return sorted(tasks.values(), key=lambda t: t.get("created_at", 0), reverse=True)[:100]

@app.delete("/api/tasks/{task_id}")
async def delete_task(task_id: str):
    if task_id not in tasks:
        raise HTTPException(404, "Task not found.")
    t = tasks.pop(task_id)
    if t.get("result"):
        for d in [IMAGES_DIR, VIDEOS_DIR]:
            fp = d / t["result"].get("filename", "")
            if fp.exists(): fp.unlink()
    return {"deleted": task_id}

@app.get("/api/health")
async def health():
    return {"status": "ok", "ltx_key_set": bool(LTX_API_KEY),
            "groq_key": bool(GROQ_API_KEY), "video_model": VIDEO_MODEL,
            "video_resolution": VIDEO_RESOLUTION, "video_duration": VIDEO_DURATION,
            "video_fps": VIDEO_FPS, "ffmpeg": _ffmpeg_available(),
            "active_tasks": sum(1 for t in tasks.values() if t["status"] == "running"),
            "total_tasks": len(tasks)}

@app.get("/", include_in_schema=False)
async def serve_root():
    idx = STATIC_DIR / "index.html"
    if idx.exists():
        return FileResponse(str(idx), media_type="text/html")
    return JSONResponse({"error": "index.html missing", "hint": "Copy index.html to static/"}, 404)

app.mount("/generated", StaticFiles(directory=str(GENERATED_DIR)), name="generated")
app.mount("/",          StaticFiles(directory=str(STATIC_DIR), html=True), name="static")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="127.0.0.1", port=4000, reload=False)